### ISSUE TITLE
Determine data I/O needs with Uncharted

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/beaker-climate-data-utility#2]
Assess how data should enter environment and be saved. Are they as datasets in TDS? If `dataset a` is regridded do we now have `dataset b` or is it some modification to `dataset a` with a new file created/saved to S3?

**Comment by Sorrento110** [comment]
The decision here is as follows: Modified data should be saved as a new dataset in the HMI server and uploaded via file-upload endpoints to HMI server storage.
